spring:
  application:
    name: multiple-datasource

    datasource:
      primary:
        url: jdbc:mysql://localhost:3306/user-service?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
      secondary:
        url: jdbc:mysql://localhost:3306/user-service-slave?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

    hikari:
      primary:
        pool-name: PrimaryHikariCP
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000
      secondary:
        pool-name: SecondaryHikariCP
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        connection-timeout: 30000
        max-lifetime: 1800000
